CREATE DATABASE myToDoListDb

CREATE TABLE myToDos(
Id INT IDENTITY(1,1) PRIMARY KEY,
Title varchar(200),
IsDone BIT,
Date DateTime
);

--ALTER LOGIN sa WITH PASSWORD = 'ceb13579!@';  --> Nu am schimbat parola, este to aceeasi

--ALTER LOGIN sa ENABLE;

ALTER TABLE myToDos
ALTER COLUMN Title NVARCHAR(200) NOT NULL;

ALTER TABLE myToDos
ALTER COLUMN IsDone BIT NOT NULL;

ALTER TABLE myToDos
ALTER COLUMN Date DATETIME NOT NULL;

ALTER TABLE myToDos
ALTER COLUMN IsDone BIT;


CREATE TABLE ToDos(
Id INT IDENTITY(1,1) PRIMARY KEY,
TITLE VARCHAR(200) NOT NULL,
IsDone BIT,
Date DATETIME NOT NULL
);

DROP TABLE myToDos;


SELECT * FROM ToDos;